### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by LuposX** [theonetruekn/interactive-learning#3]
This tracks stuff that needs to be implemented:
- [ ] Make an example for few Shot
- [ ] Only output the files in the current folder of tool List_Files, update example, update description
- [ ] Test and Compare llama3, Phi3, Gemma2
- [ ] Make Meta-Tokenizer more Robust by using tags e.g. [Action] list_files [/Action]
- [ ] Meta-Tokenizer backtrack, if it doesn't follow the ReAct format
